---
- hosts: all
  vars:
    ansible_ssh_common_args: '-o ConnectTimeout=120'
  tasks:
    - name: Run Python HTTP server
      command: python3 -m http.server
      async: 300
      poll: 0
    
    - name: Wait for server to be up
      wait_for:
        host: localhost
        port: 8000
        delay: 10
        timeout: 300