---
- hosts: all
  vars:
    ansible_ssh_common_args: '-o ConnectTimeout=60'
    ansible_ssh_retries: 3
  tasks:
    - name: Install jupyter
      pip:
        name: jupyter
        state: present
      become: yes

    - name: Start jupter server in a tmux session
      shell: |
        tmux new-session -d -s jupyter_session 'jupyter notebook --ip 0.0.0.0 --no-browser --NotebookApp.allow_origin="*" --NotebookApp.ip="0.0.0.0" --NotebookApp.token="43e69650-980a-4b33-82ce-50601e561834"'
      args:
        executable: /bin/bash

    # - name: Run VLLM API server
    #   # command: python3 -m vllm.entrypoints.openai.api_server --model meta-llama/Meta-Llama-3-8B-Instruct >> vllm_server.log 2>&1
    #   shell: nohup python3 -m vllm.entrypoints.openai.api_server --model facebook/opt-125m &
    #   # command: vllm serve facebook/opt-125m >> vllm_server.log 2>&1
    #   environment:
    #     HF_TOKEN: "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"
    #   async: 3
    #   poll: 0
    #   # register: vllm_server

    - name: Wait for juyter server to be up
      wait_for:
        host: 127.0.0.1
        port: 8888
        delay: 5
        timeout: 800

    # - name: Perform health check on VLLM API server
    #   uri:
    #     url: http://localhost:8000/v1/models
    #     method: GET
    #   register: health_check
    #   retries: 10
    #   delay: 30
    #   until: health_check.status == 200

    # - name: Print the output
    #   debug:
    #     var: vllm_server.stdout_lines


    # - name: Wait for server to be up
    #   wait_for:
    #     host: localhost
    #     port: 8000
    #     delay: 10
    #     timeout: 300